apiVersion: v1
kind: Service
metadata:
  #unique key of service instance
  name: azure-vote-back
  labels:
    app: azure-vote-back
spec:
  ports:
    # Accept traffic sent to port 6379
    - port: 6379
  selector:
    # Loadbalance traffic across Pods matching this label selector
    app: azure-vote-back
  type: LoadBalancer
